<a href="https://colab.research.google.com/github/Tanveer87/Machine-Deep-Learning/blob/master/03_Decision_Tree_Regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/ML DL DATASET/Salary Data (1).csv')

In [3]:
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object 
 2   Education Level      373 non-null    object 
 3   Job Title            373 non-null    object 
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB


In [5]:
# Find out the null value
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Years of Experience'] = df['Years of Experience'].fillna(df['Years of Experience'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [7]:
most_frequent_category = df['Gender'].mode().iloc[0]
df['Gender'].fillna(most_frequent_category, inplace = True)

most_frequent_category = df['Job Title'].mode().iloc[0]
df['Job Title'].fillna(most_frequent_category, inplace = True)

most_frequent_category = df['Education Level'].mode().iloc[0]
df['Education Level'].fillna(most_frequent_category, inplace = True)

In [8]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

# **Encoding**

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [11]:
df['Gender'] = le.fit_transform(df['Gender'])
df['Education Level'] = le.fit_transform(df['Education Level'])
df['Job Title'] = le.fit_transform(df['Job Title'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  375 non-null    float64
 1   Gender               375 non-null    int64  
 2   Education Level      375 non-null    int64  
 3   Job Title            375 non-null    int64  
 4   Years of Experience  375 non-null    float64
 5   Salary               375 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 17.7 KB


In [13]:
x = df.drop(columns = ['Salary'])
y = df['Salary']

In [14]:
x

Age  Gender  Education Level  Job Title  Years of Experience
0    32.0       1                0        159                  5.0
1    28.0       0                1         17                  3.0
2    45.0       1                2        130                 15.0
3    36.0       0                0        101                  7.0
4    52.0       1                1         22                 20.0
..    ...     ...              ...        ...                  ...
370  35.0       0                0        131                  8.0
371  43.0       1                1         30                 19.0
372  29.0       0                0         70                  2.0
373  34.0       1                0        137                  7.0
374  44.0       0                2        110                 15.0

[375 rows x 5 columns]

In [15]:
y

0       90000.0
1       65000.0
2      150000.0
3       60000.0
4      200000.0
         ...   
370     85000.0
371    170000.0
372     40000.0
373     90000.0
374    150000.0
Name: Salary, Length: 375, dtype: float64

<font color = "lime">**K fold Cross Validation**


In [17]:
# Import Decision Tree Regressor Library
from sklearn.tree import DecisionTreeRegressor

DTRegressor = DecisionTreeRegressor(criterion = 'squared_error',  # Calculate the impurity
                                    max_depth = 10,               # Depth of Total tree from first to last
                                    min_samples_split = 2,        # The minimum number of samples required to split an internal node
                                    min_samples_leaf = 1,         # At least 1 sample node to require at leaf node
                                    max_features = None,          # How many features consider while splitting the tree, None= Max no of features are considered
                                    max_leaf_nodes = None,        # How many leaf nodes in my decision tree
                                    min_impurity_decrease = 0.0   # Handling Impurity value
                                    )

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

k_flod = KFold(10)

results1 = cross_val_score(DTRegressor, x, y, cv = k_flod, scoring = 'neg_mean_squared_error')             # Negative Mean Square Error
results2 = cross_val_score(DTRegressor, x, y, cv = k_flod, scoring = 'neg_mean_absolute_percentage_error')
results3 = cross_val_score(DTRegressor, x, y, cv = k_flod, scoring = 'r2')

In [20]:
# negative MSE
results1

array([-7.76973684e+08, -9.48907899e+08, -4.73408249e+08, -3.13252260e+08,
       -1.54203982e+08, -1.60784909e+08, -1.24215106e+08, -5.99642720e+07,
       -9.06221781e+07, -2.44668202e+08])

In [21]:
# negative MAPE
results2

array([-0.21117195, -0.1851096 , -0.17468594, -0.13768211, -0.09969705,
       -0.10815822, -2.77862593, -0.05422001, -0.04437884, -0.06539094])

In [22]:
overall_MAE_percentage = sum(results2) / len(results2)
print(abs(overall_MAE_percentage) * 100)

38.591205931446176


In [23]:
results3   # R2

array([0.68054907, 0.63063544, 0.83349364, 0.90855866, 0.92472063,
       0.93366214, 0.93883852, 0.97275675, 0.95714951, 0.89191767])

In [24]:
overall_R2= sum(results3) / len(results3)
print(overall_R2)

0.8672282038840805


<font color = "lime"> Find What Metrics Support

In [ ]:
import sklearn
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',